# Generated by Django 2.2 on 2021-11-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storiesapp', '0002_auto_20211129_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystory',
            name='img',
            field=models.ImageField(default=1, upload_to='stories'),
            preserve_default=False,
        ),
    ]
